### ISSUE TITLE
Here is some problem 'Scripts not permitted to use new java.util.Random' when I run the job now.

### ISSUE THREAD

**Issue by glossary95** [ccpwcn/jenkins2_pipeline_parallel#1]
who can help to find out the issue. the first row(import java.util.Random) is error as follow:

org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: Scripts not permitted to use new java.util.Random

**Comment by ccpwcn** [comment]
Job->Configure->Use Groovy Sandbox, Don't checked it.
